version: '3.7'
services:
    web:
        restart: always
        build: .
        container_name: RegistrationUI
        expose:
            - 8000
        env_file:
            - ./.env
        command: "gunicorn registrationUI.wsgi:application --bind 0.0.0.0:8000"
        volumes: 
            - static_volume:/code/static
        depends_on:
            - db
    db:
        restart: always
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    nginx:
        restart: always
        build: ./nginx
        ports:
            - 1337:80
        volumes:
            - static_volume:/home/app/web/static
        depends_on:
            - web
volumes: 
    postgres_data: 
    static_volume: