# Generated by Django 3.0.4 on 2020-09-16 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('note', models.TextField(blank=True, max_length=300, verbose_name='Beschreibung')),
                ('max_registrations', models.DecimalField(decimal_places=0, default=10, max_digits=2, verbose_name='Max. Teilnehmeranzahl')),
                ('registration_starting_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum: Öffnung der Registrierung')),
                ('registration_closing_date', models.DateField(default=datetime.datetime(2021, 9, 16, 20, 23, 21, 699559, tzinfo=utc), verbose_name='Datum: Schließung der Registrierung')),
                ('infinite_registration_period', models.BooleanField(default=False, verbose_name='Unbegrenz lange Registrieungsphase')),
                ('day', models.CharField(blank=True, choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag'), ('Sa', 'Sammstag'), ('So', 'Sonntag')], max_length=2, null=True, verbose_name='Tag')),
                ('advertise', models.BooleanField(default=True, help_text='Zeigt das Projekt in der List auf der Startseite an', verbose_name='Bewerbung des Projekts')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.CharField(choices=[('m', 'Schüler'), ('f', 'Schülerin')], max_length=1, verbose_name='Schüler/in')),
                ('forename', models.CharField(max_length=25, verbose_name='Vorname')),
                ('surname', models.CharField(max_length=25, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=50, verbose_name='E-Mail')),
                ('address', models.CharField(max_length=70, verbose_name='Addresse')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Telefonnummer')),
                ('school', models.CharField(max_length=40, verbose_name='Schule')),
                ('school_class', models.CharField(max_length=5, verbose_name='Klasse')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Warum möchtest du bei uns mitmachen?')),
                ('approved', models.BooleanField(default=False, verbose_name='Angenommen')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.Project')),
            ],
        ),
    ]
