# Generated by Django 3.0.4 on 2020-09-05 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('note', models.TextField(blank=True, max_length=300, verbose_name='Beschreibung')),
                ('max_registrations', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Max. Teilnehmeranzahl')),
                ('registration_closing_date', models.DateField(blank=True, null=True)),
                ('day', models.CharField(choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag'), ('Sa', 'Sammstag'), ('So', 'Sonntag')], default='MO', max_length=2)),
                ('candidates', models.ManyToManyField(related_name='candidates', to='ui.Candidate')),
                ('confirmed_candidates', models.ManyToManyField(related_name='confirmed_candidates', to='ui.Candidate')),
            ],
        ),
    ]
