# Generated by Django 3.0.4 on 2020-09-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='project',
            name='confirmed_candidates',
        ),
        migrations.AddField(
            model_name='candidate',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Angenommen'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ui.Project'),
            preserve_default=False,
        ),
    ]
