# Generated by Django 3.2.4 on 2021-06-22 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='text',
            new_name='application',
        ),
        migrations.AddField(
            model_name='candidate',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-Mail eines Elternteils'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parent_forename',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Vorname eines Elternteils'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parent_surname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nachname eines Elternteils'),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_application',
            field=models.BooleanField(default=True, help_text='Ermöglicht "Warum möchtest du bei uns mitmachen?"-Textfeld', verbose_name='Textfeld anzeigen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='registration_closing_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 1, 0, 0, tzinfo=utc), verbose_name='Datum: Schließung der Registrierung'),
        ),
    ]
