# Generated by Django 3.2.12 on 2022-05-05 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20210622_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registration_closing_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 0, 0, tzinfo=utc), verbose_name='Datum: Schließung der Registrierung'),
        ),
    ]
