# Generated by Django 3.0.4 on 2020-09-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20200906_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='school',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='school_class',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
