# Generated by Django 3.2.12 on 2022-06-10 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_project_registration_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registration_closing_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 0, 0, tzinfo=utc), verbose_name='Datum: Schließung der Registrierung'),
        ),
    ]
