# Generated by Django 3.0.4 on 2020-09-06 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20200906_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='infinite_registration_period',
            field=models.BooleanField(default=False, verbose_name='Unbegrenz lange Registrieungsphase'),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_starting_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum: Öffnung der Registrierung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='day',
            field=models.CharField(blank=True, choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag'), ('Sa', 'Sammstag'), ('So', 'Sonntag')], max_length=2, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_registrations',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2, verbose_name='Max. Teilnehmeranzahl'),
        ),
        migrations.AlterField(
            model_name='project',
            name='registration_closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum: Schließung der Registrierung'),
        ),
    ]
