# Generated by Django 3.0.4 on 2020-09-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20200906_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advertise',
            field=models.BooleanField(default=True, help_text='Zeigt das Projekt in der List auf der Startseite an', verbose_name='Bewerbung des Projekts'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='forename',
            field=models.CharField(max_length=25, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.Project'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school',
            field=models.CharField(max_length=40, verbose_name='Schule'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school_class',
            field=models.CharField(max_length=5, verbose_name='Klasse'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Nachname'),
        ),
    ]
