# Generated by Django 3.2.20 on 2023-08-25 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_alter_project_registration_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='student',
            field=models.CharField(choices=[('f', 'Liebe'), ('m', 'Lieber'), ('d', 'Liebe*r')], max_length=1, verbose_name='Bevorzugte Anrede'),
        ),
        migrations.AlterField(
            model_name='project',
            name='registration_closing_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 0, 0, tzinfo=utc), verbose_name='Datum: Schließung der Registrierung'),
        ),
    ]
