# Generated by Django 4.2.5 on 2023-09-11 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_auto_20230825_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='address',
            new_name='address_street',
        ),
        migrations.AlterField(
            model_name='project',
            name='registration_closing_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 31, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Datum: Schließung der Registrierung'),
        ),
    ]
