# Generated by Django 3.0.4 on 2020-09-11 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20200911_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registration_closing_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 11, 15, 43, 31, 773048, tzinfo=utc), verbose_name='Datum: Schließung der Registrierung'),
        ),
    ]
